name: black_history_gram
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^2.1.0
  form_field_validator: ^1.1.0
  flutter_rating_bar: ^4.0.0
  audio_video_progress_bar: ^0.4.0
  youtube_player_flutter: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/facebook.png
    - assets/twitter.png
    - assets/google.png
    - assets/rendzio.png
    - assets/dummy.jpg
    - assets/regular-gig-image.png
    - assets/paymentmethod1.png
    - assets/paymentmethod2.png
    - assets/paymentmethod3.png
    - assets/toiletcleaner.png
    - assets/share_icon.png
    - assets/scanqrcode.png
    - assets/notification_icon.png
    - assets/splash_screen.jpg
    - assets/images/rendzio.png
    - assets/viewall_icon.png
    - assets/pressed_bookmark_icon.png
    - assets/unpressed_bookmark_icon.png
    - assets/all_icon.png
    - assets/audiobooks_icon.png
    - assets/books_icon.png
    - assets/magazine_icon.png
    - assets/documents_icon.png
    - assets/podcasts_icon.png
    - assets/sheetmusic.png
    - assets/snapshots.png
    - assets/zoomin_icon.png
    - assets/zoomout_icon.png
    - assets/cart_icon.png
    - assets/backarrow.png
    - assets/booknumber_icon.png
    - assets/settings_icon.png
    - assets/search_btn.png
    - assets/email_icon.png
    - assets/add_icon.png
    - assets/arrow_icon1.png
    - assets/arrow_icon2.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
